import { defaultConfig, defaultVars, type PromptConfig, type PromptVars } from "./promptBuilder";

export interface Preset {
  id: string;
  label: string;
  sub: string;
  vars: Partial<PromptVars>;
  config: Partial<PromptConfig>;
}

export const PRESETS: Preset[] = [
  {
    id: "rashidah",
    label: "Rashidah Wangara",
    sub: "Warm luxury · signature · React",
    vars: {},
    config: {},
  },
  {
    id: "aminay",
    label: "Dr. Amina Yusuf",
    sub: "Clinical trust · ultra · Next.js",
    vars: {
      name: "Dr. Amina Yusuf",
      shortName: "Amina",
      role: "Clinical Psychologist & Trauma Specialist",
      credentials: "Ph.D. Clinical Psychology, Registered Clinical Psychologist",
      location: "Kilimani, Nairobi",
      serviceArea: "in-person in Kilimani, Nairobi & online across Africa",
      tagline: "Trauma held gently, safely, scientifically.",
      tagline2: "You are not broken. You are healing.",
      tagline3: "Evidence first. Humanity always.",
      years: "16",
      clients: "3,100+",
      workshops: "95+",
      rating: "5.0/5",
      reviews: "310+",
      email: "hello@aminayusuf.co.ke",
      phone: "+254 733 111 222",
      whatsapp: "254733111222",
      hours: "Mon–Fri • 9:00am – 5:00pm EAT",
      primary: "#1B3A34",
      primaryDeep: "#0E201C",
      background: "#F7F8F5",
      parchment: "#E9EDE6",
      accent: "#7A5C3E",
      gold: "#B08D57",
      fontDisplay: "Newsreader",
      fontBody: "Public Sans",
    },
    config: { depth: "ultra", tone: "clinical-trust", tech: "nextjs-tailwind", features: ["booking", "faq", "newsletter", "testimonials", "animations", "whatsapp"] },
  },
  {
    id: "kwame",
    label: "Kwame Mensah",
    sub: "Editorial bold · signature · HTML",
    vars: {
      name: "Kwame A. Mensah",
      shortName: "Kwame",
      role: "Stress Coach & Performance Psychologist",
      credentials: "MSc Sport & Exercise Psychology, ICF Certified Coach",
      location: "Accra, Ghana",
      serviceArea: "in-person in Accra & online worldwide",
      tagline: "Burn bright. Don't burn out.",
      tagline2: "High performers deserve therapy, not a hug-up.",
      tagline3: "Pressure is a sport. Learn to play it.",
      years: "9",
      clients: "1,100+",
      workshops: "240+",
      rating: "4.8/5",
      reviews: "220+",
      email: "hello@kwamemensah.co.gh",
      phone: "+233 24 555 7788",
      whatsapp: "233245557788",
      hours: "Mon–Fri • 7:00am – 4:00pm GMT",
      primary: "#2B1A14",
      primaryDeep: "#1A0F0B",
      background: "#FBF6F0",
      parchment: "#F0E4D6",
      accent: "#C2542A",
      gold: "#D9A441",
      fontDisplay: "Playfair Display",
      fontBody: "Inter",
    },
    config: { depth: "signature", tone: "editorial-bold", tech: "html-tailwind", features: ["booking", "speaking", "testimonials", "faq", "animations", "whatsapp"] },
  },
  {
    id: "sofia",
    label: "Sofia Ndlovu",
    sub: "Soft minimal · essential · React",
    vars: {
      name: "Sofia Ndlovu",
      shortName: "Sofia",
      role: "Counselling Psychologist",
      credentials: "MA Counselling Psychology, Licensed Psychologist",
      location: "Cape Town, South Africa",
      serviceArea: "online only, across Africa & Europe",
      tagline: "Slow down. You're still here.",
      tagline2: "Gentle therapy for tired, tender people.",
      tagline3: "Quiet is a place you can rest.",
      years: "7",
      clients: "640+",
      workshops: "40+",
      rating: "4.9/5",
      reviews: "150+",
      email: "hello@sofia_ndlovu.co.za",
      phone: "+27 82 333 9090",
      whatsapp: "27823339090",
      hours: "Tue & Thu • 9:00am – 1:00pm SAST",
      primary: "#31473F",
      primaryDeep: "#22332C",
      background: "#FCFBF8",
      parchment: "#F1EEE7",
      accent: "#A8896B",
      gold: "#C0A883",
      fontDisplay: "Cormorant Garamond",
      fontBody: "Lato",
    },
    config: { depth: "essential", tone: "soft-minimal", tech: "react-vite-tailwind", features: ["booking", "faq", "newsletter"] },
  },
];

export function applyPreset(p: Preset): { vars: PromptVars; config: PromptConfig } {
  return {
    vars: { ...defaultVars, ...p.vars },
    config: { ...defaultConfig, ...p.config, features: p.config.features ?? defaultConfig.features },
  };
}
